name: 'dbt_migrations'
version: '0.1.0'

require-dbt-version: ">=0.15.1"

config-version: 2

source-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]
macro-paths: ["macros"]
log-path: "logs"
